name: Docker Image CI

on:
  push:
    tags: ["*"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: docker build . -f Dockerfile -t ${{secrets.DOCKER_USER}}/certbot-dns-websupport-v2:${{github.ref_name}} -t ${{secrets.DOCKER_USER}}/certbot-dns-websupport-v2:latest
    - name: Docker push
      run: docker image push --all-tags ${{secrets.DOCKER_USER}}/certbot-dns-websupport-v2